---
- name: Deploy API Uptime Monitor Docker App
  hosts: localhost
  become: true
  vars:
    docker_image: dracon24/api-monitor:latest
    container_name: api-monitor
    exposed_port: 4000

  tasks:

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop existing container (if running)
      block:
        - name: Attempt to stop container
          command: docker stop "{{ container_name }}"
      rescue:
        - debug:
            msg: "No container running with that name, skipping stop."

    - name: Remove existing container (if present)
      block:
        - name: Attempt to remove container
          command: docker rm "{{ container_name }}"
      rescue:
        - debug:
            msg: "No container to remove, skipping."

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "{{ exposed_port }}:4000"
        restart_policy: always

